package gui;

import db.dbActions;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fiftak
 */
public class klientGUI extends javax.swing.JFrame {

    /**
     * Creates new form klientGUI
     */
    private int nrKlienta=0;
    private dbActions dbA;
    public klientGUI(int nr) {
        initComponents();
        nrKlienta=nr;
        dbA=new dbActions();
        String text = dbA.showInfo(nrKlienta);
        imie_nazwiskoDisplay.setText(text);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listaProduktow = new javax.swing.JButton();
        historiaZamowien = new javax.swing.JButton();
        imie_nazwiskoDisplay = new javax.swing.JTextField();
        buttonWyloguj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Klient");

        listaProduktow.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        listaProduktow.setText("Przegladaj sklep");
        listaProduktow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaProduktowActionPerformed(evt);
            }
        });

        historiaZamowien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        historiaZamowien.setText("Historia zamówień");
        historiaZamowien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historiaZamowienActionPerformed(evt);
            }
        });

        imie_nazwiskoDisplay.setEditable(false);
        imie_nazwiskoDisplay.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        imie_nazwiskoDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imie_nazwiskoDisplayActionPerformed(evt);
            }
        });

        buttonWyloguj.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonWyloguj.setText("Wyloguj");
        buttonWyloguj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWylogujActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imie_nazwiskoDisplay)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listaProduktow, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                        .addComponent(historiaZamowien))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonWyloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(imie_nazwiskoDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaProduktow, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(historiaZamowien, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonWyloguj, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaProduktowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaProduktowActionPerformed
        // TODO add your handling code here:
        klientGUI obj1 = new klientGUI(nrKlienta);
        sklepGUI obj2 = new sklepGUI(nrKlienta);
        
        obj2.setVisible(true);
        obj1.setVisible(false);
            dispose();
    }//GEN-LAST:event_listaProduktowActionPerformed

    private void historiaZamowienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historiaZamowienActionPerformed
        // TODO add your handling code here:
        klientGUI obj1 = new klientGUI(nrKlienta);
        historiaZamowienGUI obj2 = new historiaZamowienGUI(nrKlienta);
        
        obj2.setVisible(true);
        obj1.setVisible(false);
            dispose();
    }//GEN-LAST:event_historiaZamowienActionPerformed

    private void imie_nazwiskoDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imie_nazwiskoDisplayActionPerformed
        
    }//GEN-LAST:event_imie_nazwiskoDisplayActionPerformed

    private void buttonWylogujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWylogujActionPerformed
        // TODO add your handling code here:
        klientGUI obj1 = new klientGUI(nrKlienta);
        mainFrame obj2 = new mainFrame();
        
        obj2.setVisible(true);
        obj1.setVisible(false);
            dispose();
    }//GEN-LAST:event_buttonWylogujActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(klientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(klientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(klientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(klientGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new klientGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonWyloguj;
    private javax.swing.JButton historiaZamowien;
    private javax.swing.JTextField imie_nazwiskoDisplay;
    private javax.swing.JButton listaProduktow;
    // End of variables declaration//GEN-END:variables
}
