package gui;

import db.dbActions;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Fiftak
 */
public class mainFrame extends javax.swing.JFrame {
    private dbActions dbA;
    /**
     * Creates new form mainFrame
     */
    public mainFrame() {
        initComponents();
        dbA=new dbActions();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logowanie = new javax.swing.JTextField();
        labelLogin = new javax.swing.JLabel();
        labelHaslo = new javax.swing.JLabel();
        haslo = new javax.swing.JPasswordField();
        buttonZaloguj1 = new javax.swing.JButton();
        buttonWroc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sklep Internetowy");

        logowanie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        logowanie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logowanieActionPerformed(evt);
            }
        });

        labelLogin.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labelLogin.setText("Login: ");

        labelHaslo.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        labelHaslo.setText("Hasło:");

        haslo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        buttonZaloguj1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonZaloguj1.setText("Zaloguj się");
        buttonZaloguj1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonZaloguj1ActionPerformed(evt);
            }
        });

        buttonWroc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonWroc.setText("Wróć");
        buttonWroc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonWrocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelLogin)
                            .addComponent(labelHaslo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(haslo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(buttonWroc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(118, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buttonZaloguj1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logowanie, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLogin))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(haslo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHaslo))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonZaloguj1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonWroc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void logowanieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logowanieActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_logowanieActionPerformed

        public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, "InfoBox: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void buttonZaloguj1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonZaloguj1ActionPerformed
        // TODO add your handling code here:
        mainFrame obj1 = new mainFrame();
        
        String password= new String(haslo.getPassword());
        String login = logowanie.getText();
        int result = dbA.login(password, login);
        if(result >-1)
        {
            String acc = "Zalogowano na konto nr " + result;
            infoBox(acc, "Powodzenie");
            klientGUI obj2 = new klientGUI(result);
            obj2.setVisible(true);
            obj1.setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_buttonZaloguj1ActionPerformed

    private void buttonWrocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonWrocActionPerformed
        // TODO add your handling code here:
        mainFrame obj1 = new mainFrame();
        startingFrame obj2 = new startingFrame();
        
        obj2.setVisible(true);
        obj1.setVisible(false);
            dispose();
    }//GEN-LAST:event_buttonWrocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFrame().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonWroc;
    private javax.swing.JButton buttonZaloguj1;
    private javax.swing.JPasswordField haslo;
    private javax.swing.JLabel labelHaslo;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JTextField logowanie;
    // End of variables declaration//GEN-END:variables
}
