/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.sun.glass.events.KeyEvent;
import db.dbActions;
import java.util.Arrays;
import javax.swing.JOptionPane;
import oracle.net.aso.a;

/**
 *
 * @author Fiftak
 */
public class rejestracjaGUI extends javax.swing.JFrame {

    private dbActions dbA;

    /**
     * Creates new form rejestracjaGUI
     */
    public rejestracjaGUI() {
        initComponents();
        dbA=new dbActions();
    }
    public rejestracjaGUI(dbActions dbA) {
        initComponents();
        this.dbA=dbA;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelEmail = new javax.swing.JLabel();
        rejestracjaEmail = new javax.swing.JTextField();
        rejestracjaNazwisko = new javax.swing.JTextField();
        labelHaslo = new javax.swing.JLabel();
        buttonRejestracja = new javax.swing.JButton();
        rejestracjaTelefon = new javax.swing.JTextField();
        rejestracjaImie1 = new javax.swing.JTextField();
        labelNazwisko = new javax.swing.JLabel();
        labelImie = new javax.swing.JLabel();
        labelTelefon = new javax.swing.JLabel();
        rejestracjaAdres = new javax.swing.JTextField();
        labelTelefon1 = new javax.swing.JLabel();
        rejestracjaHaslo1 = new javax.swing.JPasswordField();
        rejestracjaPowtorz = new javax.swing.JPasswordField();
        labelHaslo1 = new javax.swing.JLabel();
        burronWroc = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rejestracja");

        labelEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelEmail.setText("Podaj email:");

        rejestracjaEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rejestracjaEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejestracjaEmailActionPerformed(evt);
            }
        });

        rejestracjaNazwisko.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rejestracjaNazwisko.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rejestracjaNazwiskoKeyTyped(evt);
            }
        });

        labelHaslo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHaslo.setText("Podaj hasło:");

        buttonRejestracja.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        buttonRejestracja.setText("Zajerestruj");
        buttonRejestracja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRejestracjaActionPerformed(evt);
            }
        });

        rejestracjaTelefon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rejestracjaTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejestracjaTelefonActionPerformed(evt);
            }
        });
        rejestracjaTelefon.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rejestracjaTelefonKeyTyped(evt);
            }
        });

        rejestracjaImie1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rejestracjaImie1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                rejestracjaImie1KeyTyped(evt);
            }
        });

        labelNazwisko.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelNazwisko.setText("Podaj Nazwisko:");

        labelImie.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelImie.setText("Podaj Imię:");

        labelTelefon.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTelefon.setText("Podaj Telefon:");

        rejestracjaAdres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        labelTelefon1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelTelefon1.setText("Podaj adres:");

        rejestracjaHaslo1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        rejestracjaPowtorz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        labelHaslo1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelHaslo1.setText("Powtórz hasło:");

        burronWroc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        burronWroc.setText("Wróć");
        burronWroc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                burronWrocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNazwisko)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelEmail)
                            .addComponent(labelHaslo)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelHaslo1)
                                    .addComponent(labelImie))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rejestracjaHaslo1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rejestracjaPowtorz, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rejestracjaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rejestracjaImie1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rejestracjaNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTelefon)
                                    .addComponent(labelTelefon1))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rejestracjaAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(rejestracjaTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(buttonRejestracja, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(burronWroc, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEmail)
                            .addComponent(rejestracjaEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHaslo)
                            .addComponent(rejestracjaHaslo1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHaslo1)
                            .addComponent(rejestracjaPowtorz, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(labelImie)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelNazwisko)
                            .addComponent(rejestracjaNazwisko, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rejestracjaImie1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefon)
                    .addComponent(rejestracjaTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefon1)
                    .addComponent(rejestracjaAdres, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRejestracja, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(burronWroc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public static void infoBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage, titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void buttonRejestracjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRejestracjaActionPerformed
        // TODO add your handling code here:
        rejestracjaGUI obj1 = new rejestracjaGUI();
        mainFrame obj2 = new mainFrame();
        String adres = rejestracjaAdres.getText();
        String email = rejestracjaEmail.getText();
        char [] haslo = rejestracjaHaslo1.getPassword();
        String haslo1 = new String(haslo);
        char [] powtorzHaslo = rejestracjaPowtorz.getPassword();
        String powtorz = new String(powtorzHaslo);
        String imie1 = rejestracjaImie1.getText();
        String nazwisko = rejestracjaNazwisko.getText();
        String telefon = rejestracjaTelefon.getText();
        if(!haslo1.equals(powtorz))
        {
            infoBox("Hasla nie są identyczne", "Haslo!");
        }
        else if(!(adres==""||email==""||haslo1==""||imie1==""||nazwisko==""||telefon==""))
        {
            boolean result = dbA.createUser(adres, email, haslo1, imie1, nazwisko, telefon); 
            if(result)
            {
                infoBox("Rejestracja przebiegła pomyślnie!", "Zarejestrowano!");
                obj2.setVisible(true);
                obj1.setVisible(false);
                dispose();
                
            }
            else
            {
                infoBox("Wystąpił błąd podczas rejestracji. Proszę sprawdzić podane dane", "Błąd!");
            }
        }
        else
        {
            infoBox("Jedno lub więcej pól jest puste. Proszę je uzupełnić", "Puste pole");
        }
    }//GEN-LAST:event_buttonRejestracjaActionPerformed

    private void rejestracjaEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejestracjaEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rejestracjaEmailActionPerformed

    private void rejestracjaTelefonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rejestracjaTelefonKeyTyped
        char key=evt.getKeyChar();
        if(!(Character.isDigit(key))||(key==KeyEvent.VK_BACKSPACE)||(key==KeyEvent.VK_DELETE))
        {
            evt.consume();
        }
    }//GEN-LAST:event_rejestracjaTelefonKeyTyped

    private void rejestracjaImie1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rejestracjaImie1KeyTyped
        char key=evt.getKeyChar();
        if(!((key>64&&key<91)||(key>96&&key<123)))
        {
            evt.consume();
        }
    }//GEN-LAST:event_rejestracjaImie1KeyTyped

    private void rejestracjaNazwiskoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_rejestracjaNazwiskoKeyTyped
        char key=evt.getKeyChar();
        if(!((key>64&&key<91)||(key>96&&key<123)||key==45))
        {
            evt.consume();
        }
    }//GEN-LAST:event_rejestracjaNazwiskoKeyTyped

    private void rejestracjaTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejestracjaTelefonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rejestracjaTelefonActionPerformed

    private void burronWrocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_burronWrocActionPerformed
        // TODO add your handling code here:
        rejestracjaGUI obj1 = new rejestracjaGUI();
        startingFrame obj2 = new startingFrame();
        
        obj2.setVisible(true);
        obj1.setVisible(false);
            dispose();
    }//GEN-LAST:event_burronWrocActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rejestracjaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rejestracjaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rejestracjaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rejestracjaGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rejestracjaGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton burronWroc;
    private javax.swing.JButton buttonRejestracja;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelHaslo;
    private javax.swing.JLabel labelHaslo1;
    private javax.swing.JLabel labelImie;
    private javax.swing.JLabel labelNazwisko;
    private javax.swing.JLabel labelTelefon;
    private javax.swing.JLabel labelTelefon1;
    private javax.swing.JTextField rejestracjaAdres;
    private javax.swing.JTextField rejestracjaEmail;
    private javax.swing.JPasswordField rejestracjaHaslo1;
    private javax.swing.JTextField rejestracjaImie1;
    private javax.swing.JTextField rejestracjaNazwisko;
    private javax.swing.JPasswordField rejestracjaPowtorz;
    private javax.swing.JTextField rejestracjaTelefon;
    // End of variables declaration//GEN-END:variables
}
